TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Models/Campos_Dashboard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TCRD_GeneracionSentencia.Models
{
    public class Campos_Dashboard
    {
        public int ID { get; set; }
        public string Nombre { get; set; }

        public string Estatus { get; set; }
        public int ID_Estatus { get; set; }
        public string Usuario { get; set; }
        public DateTime Fecha_Registro { get; set; }
    }
}

TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Controllers/CamposDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCRD_GeneracionSentencia.Models;

namespace TCRD_GeneracionSentencia.Controllers
{
    public class CamposDashboardController : Controller
    {
        // GET: CamposDashboard
        public ActionResult Index()
        {
            var campos = Helpper.CamposDashboardHelpper.GetCampos();

            return View(campos);
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(Campos_Dashboard campo)
        {
            if (ModelState.IsValid)
            {

                return Json(new
                {
                    success = Helpper.CamposDashboardHelpper.CreateCampo(campo)

                });


            }
            else
            {
                return Json(false);
            }
        }

        public ActionResult Registros()
        {

            var registrosDashboard = Helpper.CamposDashboardHelpper.GetRegistros();

            return View(registrosDashboard);
        }

        public ActionResult CreateRegistro()
        {
             var campos = Helpper.CamposDashboardHelpper.GetCampos();
            return View(campos);
        }

        [HttpPost]
        public ActionResult CreateRegistro(List<RegistrosDashboard> registros)
        {
            var success = false;
            
            if (ModelState.IsValid)
            {

                foreach (var registro in registros)
                {
                    success = Helpper.CamposDashboardHelpper.CreateRegistro(registro);
                }

                return Json(success);

            }
            else
            {
                return Json(success);
            }
        }


    }
}

TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Views/CamposDashboard/Create.cshtml

@{
    ViewBag.Title = "Create";
}

<style>

    #guardar-campo {
        color: #fff;
        background-color: #79222d !important;
        border-color: #79222e !important;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">Crear un Magistrado</div>
                <div class="card-body">
                    <div class="card-title">
                        <h3 class="text-center title-2">Datos</h3>
                    </div>
                    <hr>
                    <form action="" method="post" novalidate="novalidate">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="cc-nom_magistrado" class="control-label mb-1">Nombre del Campo</label>
                                    <input id="campo" name="nom_magistrado" type="text" class="form-control " value="" data-val="true" data-val-required="Introduzca el nombre del Magistrado"
                                           data-val-num_expp="Introduce el nombre del campo" placeholder="Introduzca el nombre del campo"
                                           autocomplete="campo">
                                    <span class="help-block" data-valmsg-for="campo" data-valmsg-replace="true"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <label for="fecha_exp" class="control-label mb-1">Estatus</label>
                                <div class="input-group date">
                                    <select id="estatus" name="estatus" class="form-control" >
                                        <option selected value="1">Activo</option>
                                        <option value="2">Inactivo</option>
                                    </select>
                                           

                                </div>
                            </div>
                        </div>

                        <div>
                            <button id="guardar-campo" type="submit" class="btn btn-md btn-info btn-block">
                                <i class="fa fa-save fa-lg"></i>&nbsp;
                                <span id="payment-button-info">Guardar Campo</span>
                                <span id="payment-button-info2" style="display:none;">Guardando…</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>

</div>


<script src="~/Content/vendor/jquery-3.2.1.min.js"></script>
<script>
    var id = 0;

    $(document).ready(function () {


        $("#guardar-campo").click(function (e) {
            e.preventDefault();

            var campo = $("#campo").val();
            var estatus = $('#estatus').val();
            alert(estatus);

            var formData = new FormData();
            formData.append("Nombre", campo);
            formData.append("ID_Estatus", estatus);
            $.ajax({
                type: "POST",
                url: "Create",
                data: formData,
                contentType: false,
                processData: false,
                success: function (response) {
                    if (response.success === true) {
                        window.location.reload();
                        alert("Accion Realizada Correctamente");

                    } else {
                        console.log("No se pudo registrar el Magistrado");
                    }
                },

                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });

    });

</script>

TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Views/CamposDashboard/CreateRegistro.cshtml

@{
    ViewBag.Title = "Create Registro";
}

<style>
    #guardar-registro {
        color: #fff;
        background-color: #79222d !important;
        border-color: #79222e !important;
    }
</style>



<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">Crear un Registro</div>
                <div class="card-body">
                    <div class="card-title">
                        <h3 class="text-center title-2">Datos del Registro</h3>
                    </div>
                    <hr>
                    <form id="form-registros" novalidate="novalidate">
                        @foreach (var item in Model)
                        {
                            <div class="form-group">
                                <label for="@item.Nombre" class="control-label mb-1">@item.Nombre</label>
                                <input id="@item.ID" name="@item.ID" type="text" class="form-control" placeholder="@item.Nombre" value="">
                            </div>
                        }
                        <div>
                            <button id="guardar-registro" type="button" class="btn btn-md btn-info btn-block">
                                <i class="fa fa-save fa-lg"></i>&nbsp;
                                <span id="payment-button-info">Guardar Registro</span>
                                <span id="payment-button-info2" style="display:none;">Guardando…</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    var modelData = @Html.Raw(Json.Encode(Model));

    $(document).ready(function () {
        $("#guardar-registro").click(function () {
            var valores = ObtenerValoresDeCampos();
            console.log(valores);

            $.ajax({
                type: "POST",
                url: '@Url.Action("CreateRegistro", "CamposDashboard")',
                data: JSON.stringify(valores),
                contentType: "application/json; charset=utf-8",
                processData: false,
                success: function (response) {
                    if (response === true) {
                        window.location.reload();
                        alert("Registros creados exitosamente");
                    } else {
                        alert("No se pudieron crear los registros");
                    }
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });

        function ObtenerValoresDeCampos() {
            var valores = [];

            for (var i = 0; i < modelData.length; i++) {
                var idCampo = modelData[i].ID;
                var valor = $("#" + idCampo).val();

                valores.push({ IdCampo: idCampo, Valor: valor });
            }

            return valores;
        }
    });
</script>
   

TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Views/CamposDashboard/Index.cshtml
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-12">
            <!-- USER DATA-->
            <div class="user-data m-b-30">
                <h3 class="title-3 m-b-30">
                    <i class="zmdi zmdi-account-calendar"></i>Campos
                </h3>
                <div class="table-responsive table-data">
                    <table class="table">
                        <thead>
                            <tr>
                                <td>
                                </td>
                                <td>Nombre</td>
                                <td>Estado</td>
                                <td>Usuario</td>
                                <td>Fecha Creacion</td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>

                            @{

                                foreach (var item in Model)
                                {
                                                        <tr>
                                                            <td>
                                                                <label class="au-checkbox">
                                                                    <input type="checkbox">
                                                                    <span class="au-checkmark"></span>
                                                                </label>
                                                            </td>
                                                            <td>
                                                                <div class="table-data__info">
                                                                    <h6>@item.Nombre</h6>

                                                                </div>
                                                            </td>
                                                            <td>
                                                                <span class="table-data__info">@item.Estatus</span>
                                                            </td>
                                                            <td>
                                                                <span class="table-data__info">@item.Usuario</span>
                                                            </td>
                                                            <td>
                                                                <span class="table-data__info">@item.Fecha_Registro</span>
                                                            </td>
                                                            <td>
                                                                @*<span class="more">
                <i class="zmdi zmdi-edit"></i>
            </span>*@

                                                                <span data-id="@item.ID" class="more delete-button">
                                                                </span>
                                                            </td>
                                                        </tr>
                                }
                            }


                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END USER DATA-->
        </div>
    </div>
</div>



TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Views/CamposDashboard/Registros.cshtml

@{
    ViewBag.Title = "Registros";
}




<div class="container-fluid">

    <div class="row">
        <div class="col-lg-12">
            <!-- USER DATA-->
            <div class="user-data m-b-30">
                <h3 class="title-3 m-b-30">
                    <i class="zmdi zmdi-account-calendar"></i>Registros
                </h3>
                <div class="table-responsive table-data">
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Nombre</th>
                                <th>Valor</th>
                                <th>Usuario</th>
                                <th>Fecha Creacion</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <label class="au-checkbox">
                                            <input type="checkbox">
                                            <span class="au-checkmark"></span>
                                        </label>
                                    </td>
                                    <td>
                                        <div class="table-data__info">
                                            <h6>@item.Campo</h6>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="table-data__info">@item.Valor</span>
                                    </td>
                                    <td>
                                        <span class="table-data__info">@item.Usuario</span>
                                    </td>
                                    <td>
                                        <span class="table-data__info">@item.fecha_registro</span>
                                    </td>
                                    <td>
                                        <!-- Botones de acción, si es necesario -->
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
        </div>
    </div>
</div>

</div>