TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Models/Secuencia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TCRD_GeneracionSentencia.Models
{
    public class Secuencia
    {

        public string secuencia { get; set; }
        public string usuario { get; set; }
        public DateTime fecha { get; set; }

    }
}

TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Models/Sentencia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TCRD_GeneracionSentencia.Models
{
    public class Sentencia
    {

        public int id { get; set; }
        public string num_sentencia { get; set; }
        public string num_expediente { get; set; }
        public string usuario { get; set; }
        public DateTime fecha_sentencia { get; set; }
        List<Magistrado> magistrados { get; set; }
        public DateTime fecha_registro { get; set; }


    }
}

TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Controllers/SentenciasController.cs

using Microsoft.Office.Interop.Word;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TCRD_GeneracionSentencia.Models;


namespace TCRD_GeneracionSentencia.Controllers
{
    public class SentenciasController : Controller
    {

        

        // GET: Sentencias
        public ActionResult Index()
        {

            var nombre = Session["nombre"] != null ? Session["nombre"].ToString() : "";

            if (!string.IsNullOrEmpty(nombre))
            {
                var sentencias = Helpper.SentenciaHelpper.GetSentencias();

                return View(sentencias);
            }
            else return RedirectToAction("Login", "Auth");


           

        }

        public ActionResult GenerarSentencia()
        {

            var nombre = Session["nombre"] != null ? Session["nombre"].ToString() : "";

            if (!string.IsNullOrEmpty(nombre))
            {

                ViewBag.Message = "Your contact page.";
                MemoryStream memoryStream = new MemoryStream();
                ViewBag.PdfStream = memoryStream;

                return View();
            }
            else return RedirectToAction("Login", "Auth");


        }

        public ActionResult DownloadWord(string wordBase64)
        {
            byte[] wordBytes = Convert.FromBase64String(wordBase64);
            return File(wordBytes, "application/msword", "sentencia.docx");
        }

        [HttpPost]
        public ActionResult GenerarSentencia(HttpPostedFileBase archivo, Sentencia sentencia)
        {
            if (ModelState.IsValid)
            {
                string resumen = string.Empty;
                Application wordApp = null;
                Document wordDoc = null;

                try
                {
                    string ultima_secuencia = Helpper.SentenciaHelpper.GetUltimaSecuencia();
                    sentencia.num_sentencia = ultima_secuencia;
                    List<Magistrado> magistrados = Helpper.MagistradoHelpper.GetMagistrados();
                    string referenciaSentencia = "TC/0000/23";
                    string referenciaExpediente = "TC-xxxxxx-xxxx";
                    string referenciaFecha = "a los _______________________________ (____) días del mes de __________________________________ del año dos mil veintitrés (2023).";


                    string wordFilePath = Path.Combine(Server.MapPath("~/App_Data"), archivo.FileName);
                    archivo.SaveAs(wordFilePath);

                    wordApp = new Application();
                    wordDoc = wordApp.Documents.Open(wordFilePath);

                    // Modificar fecha 
                    Find findObject = wordDoc.Content.Find;
                    findObject.MatchWholeWord = true;
                    findObject.Text = referenciaFecha;
                    findObject.Replacement.Text = Helpper.ConversionFecha.ConvertirFechaATexto(sentencia.fecha_sentencia.ToString().Split(' ')[0]);
                    findObject.Execute(Replace: WdReplace.wdReplaceAll);


                    // Modificar Sentencia
                    findObject.Text = referenciaSentencia;
                    findObject.Replacement.Text = ultima_secuencia;
                    findObject.Execute(Replace: WdReplace.wdReplaceAll);

                    // Modificar Expediente
                    findObject.Text = referenciaExpediente;
                    findObject.Replacement.Text = sentencia.num_expediente;
                    findObject.Execute(Replace: WdReplace.wdReplaceAll);


                    //ELIMINAR SECCION DE FIRMAS
                    Range startRange = wordDoc.Content;
                    startRange.Find.Text = "DISPONER su publicación en el Boletín del Tribunal Constitucional.";
                    startRange.Find.Execute();


                    if (startRange.Find.Found)
                    {
                        Range endRange = wordDoc.Content;
                        endRange.Find.Text = "La presente sentencia es dada y firmada por los señores jueces del Tribunal";
                        endRange.Find.Execute();

                        if (endRange.Find.Found)
                        {
                            Range sectionRange = wordDoc.Range(startRange.End, endRange.Start);
                            sectionRange.Delete();
                        }


                        Range emptyLineRange = wordDoc.Range(endRange.Start, endRange.Start);


                        //Insertar Firmas
                        string firmas = "\r\nFirmada: ";
                        foreach (var item in magistrados)
                        {
                            Range findRange = wordDoc.Content;
                            findRange.Find.Text = item.nombre_magistrado.Trim();
                            bool textoEncontrado = findRange.Find.Execute();
                            string signo = item.firma == "Secretaria" ? "." : "; ";
                            if (textoEncontrado)
                            {
                                firmas += item.nombre_magistrado + ", " + item.firma.ToLower() + signo;

                            }

                        }
                        firmas += "\r\n\r\n";
                        emptyLineRange.Text = firmas;

                    }

                    //Seccion del Tweet
                    Range startRange2 = wordDoc.Content;
                    startRange2.Find.Text = "II. ";
                    startRange2.Find.Execute();


                    if (startRange2.Find.Found)
                    {
                        Range endRange2 = wordDoc.Content;
                        endRange2.Find.Text = "III. ";
                        endRange2.Find.Execute();

                        if (endRange2.Find.Found)
                        {
                            Range sectionRange2 = wordDoc.Range(startRange2.End, endRange2.Start);
                            resumen = sectionRange2.Text;
                        }
                        else
                        {
                            Range sectionRange2 = wordDoc.Range(startRange2.End, wordDoc.Content.End);
                            resumen = sectionRange2.Text;

                        }

                    }

                    string selloImagePath = Server.MapPath("~/Content/images/GVR.jpg");

                    if (System.IO.File.Exists(selloImagePath))
                    {
                        Paragraph lastParagraph = null;
                        foreach (Paragraph paragraph in wordDoc.Paragraphs)
                        {
                            lastParagraph = paragraph;
                        }
                        Range lastParagraphRange = lastParagraph.Range;

                        InlineShape waterMarkShape = lastParagraphRange.InlineShapes.AddPicture(selloImagePath);
                        waterMarkShape.Width = 100;
                        waterMarkShape.Height = 100;

                        lastParagraph.Alignment = WdParagraphAlignment.wdAlignParagraphRight;

                    }

                    // Convertir el Word a PDF
                    string pdfFilePath = Path.ChangeExtension(wordFilePath, ".pdf");
                    wordDoc.ExportAsFixedFormat(pdfFilePath, WdExportFormat.wdExportFormatPDF);

                    // Guardar el Word en un archivo temporal
                    string tempWordFilePath = Path.Combine(Server.MapPath("~/App_Data"), "temp.docx");
                    wordDoc.SaveAs2(tempWordFilePath);

                    // Cerrar y liberar recursos de Word
                    wordDoc.Close();
                    wordApp.Quit();
                    Marshal.ReleaseComObject(wordDoc);
                    Marshal.ReleaseComObject(wordApp);

                    byte[] pdfBytes = System.IO.File.ReadAllBytes(pdfFilePath);
                    byte[] wordBytes = System.IO.File.ReadAllBytes(tempWordFilePath);

                    MemoryStream pdfStream = new MemoryStream(pdfBytes);
                    string pdfBase64 = Convert.ToBase64String(pdfStream.ToArray());

                    string wordBase64 = Convert.ToBase64String(wordBytes);

                    // Eliminar los archivos temporales
                    System.IO.File.Delete(wordFilePath);
                    System.IO.File.Delete(pdfFilePath);
                    System.IO.File.Delete(tempWordFilePath);

                    Secuencia secuencia = new Secuencia
                    {

                        secuencia = ultima_secuencia,
                        fecha = DateTime.Now
                    };

                    Helpper.SentenciaHelpper.AddSentencia(sentencia);
                    Helpper.SentenciaHelpper.AddSecuencia(secuencia);

                    return Json(new
                    {
                        success = true,
                        pdfBase64,
                        fileBase64 = wordBase64,
                        resumen
                    });

                }
                catch (Exception ex)
                {
                    if (wordDoc != null)
                    {
                        wordDoc.Close();
                        Marshal.ReleaseComObject(wordDoc);
                    }

                    if (wordApp != null)
                    {
                        wordApp.Quit();
                        Marshal.ReleaseComObject(wordApp);
                    }

                    return Json(false);
                }
            }
            else
            {
                return Json(false);
            }
        }




TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Views/Sentencias/GenerarSentencia.cshtml

<style>
        #generar-sentencia {
            color: #fff;
            background-color: #79222d !important;
            border-color: #79222e !important;
        }

        #generar-sentencia:hover {
            color: #fff;
            background-color: #993442;
            border-color: #993442;
        }

        #descargar-documento{
           color: #fff; 
           background-color: #79222d !important; 
           border-color: #79222e !important;
        }

        #generar-tweet {
            color: #fff;
            background-color: #79222d !important;
            border-color: #79222e !important;
        }

        #generar-tweet:hover {
            color: #fff;
            background-color: #993442;
            border-color: #993442;
        }


        .tweet-container {
            background: #fdfdfd;
            padding: 1rem;
            margin-bottom: 20px;
            border-radius: 5px;
            box-shadow: 0 0 2px rgba(0, 0, 0, .1);
            display: none;
            gap: .75em;
            border: 1px solid #8ab5;
            width: 80%;
            max-width: 600px;
        }

        .tweet-container.open {
            display: grid;
        }

        .tweet-container h2 {
            font-size: 16px;
            font-weight: 600;
            color: #444;
            letter-spacing: .25px;
        }

        .h3_tweet {
            font-size: 14px;
            color: #8ab;
            font-weight: 300;
        }

        .p_tweet {
            font-size: 16px;
            color: #222;
        }

        .post-infos p {
            color: #888;
            font-size: 14px;
        }

        .date {
            color: #111;
            font-weight: 600;
        }

        .a_tweet {
            font-weight: 600;
            color: #4ad;
        }

        .a_tweet:hover {
            color: #47c;
        }

        .header, .userinfos, .post-infos {
            display: flex;
        }

        .header, .post-infos {
            justify-content: space-between;
            align-items: center;
        }

        .userinfos {
            flex-grow: 2;
            align-items: center;
        }

        figure {
            width: 50px;
            height: 50px;
            border: 1px solid #5af;
            border-radius: 50%;
            margin-right: .5rem;
        }

        .bi {
            transition: all.3s ease-in-out;
        }

        .bi-x {
            transform: scale(2);
        }

        .bi-x:hover {
            color: red;
            transform: scale(2.4);
        }

        .bi-hand-thumbs-up-fill {
            transform: scale(1.5);
        }

        .bi-hand-thumbs-up-fill:hover {
            transform: scale(1.75) rotate(-30deg);
        }

        .bi-hand-thumbs-up-fill.liked {
            color: #5af;
        }

        .hr_tweet {
            border: 1px solid #8ab;
            border-radius: 10px;
        }
    
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">Creación de la Sentencia</div>
                <div class="card-body">
                    <div class="card-title">
                        <h3 class="text-center title-2">Datos</h3>
                    </div>
                    <hr>
                    <form action="" method="post" novalidate="novalidate">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="cc-num_exp" class="control-label mb-1">Núm del Expediente</label>
                                    <input id="num_exp" name="num_exp" type="text" class="form-control num_exp" value="" data-val="true" data-val-required="Introduce el Num del Expediente"
                                           data-val-num_expp="Introduce el Núm del Expediente" placeholder="TC-XX-XXXX-XXXX"
                                           autocomplete="num_exp">
                                    <span class="help-block" data-valmsg-for="num_exp" data-valmsg-replace="true"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <label for="fecha_exp" class="control-label mb-1">Fecha de la Sentencia</label>
                                <div class="input-group date">
                                    <input id="fecha_exp" name="fecha_exp" type="text" class="form-control fecha_exp" value="@DateTime.Now" data-val="true" data-val-required="Introduce la Fecha"
                                           data-val-fecha_exp="Introduce la Fecha" autocomplete="off">

                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="archivo" class="control-label mb-1">Adjuntar archivo</label>
                            <input type="file" id="archivo" name="archivo" accept=".doc,.docx" class="form-control">

                        </div>
                        
                        <div class="row" >
                            <div class="col-4">
                                <button id="generar-sentencia" type="submit" class="btn btn-md btn-info btn-block">
                                    <i class="fa fa-save fa-lg"></i>&nbsp;
                                    <span id="payment-button-info">Generar Documento</span>
                                    <span id="payment-button-info2" style="display:none;">Generando…</span>
                                </button>
                            </div>
                            <div class="col-4">
                                <button id="generar-tweet" type="button" class="btn btn-md btn-info btn-block" hidden>
                                    <i class="fa fa-commenting fa-lg"></i>&nbsp;
                                    <span id="payment-button-info">Generar Tweet</span>
                                    <span id="payment-button-info2" style="display:none;">Generando…</span>
                                </button>
                            </div>
                            <div id="boton-container" class="col-4">

                            </div>


                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>


    <div id="container-tweet" class="tweet-container open" hidden>
        <div class="header">

            <div class="userinfos">
                <figure><img src="https://ojd.org.do/wp-content/uploads/2020/04/Tribunal-Constitucional-Logo.png" /></figure>
                <div class="name-username">
                    <h2>TCRD</h2>
                    <h3 class="h3_tweet">&#64TribunalConstRD</h3>
                </div>
            </div>
            <i class="bi bi-x"></i>
        </div>
        <div class="textarea" style="margin-bottom: 10px;">
            <p class="p_tweet" id="contenido_tweet"> </p>
            <br>
            <p class="p_tweet"><a class="a_tweet" href="https://www.tribunalconstitucional.gob.do/consultas/secretaría/sentencias/" target="_blank">https://www.tribunalconstitucional.gob.do/</a> </p>
        </div>
        <hr class="hr_tweet">
        <div class="post-infos">
            <p class="p_tweet">Posted: <span class="date">@DateTime.Now </span></p>
            <p class="p_tweet"><span class="likes-number"></span><i class="bi bi-hand-thumbs-up-fill like-btn"></i></p>
        </div>
    </div>

    <iframe id="pdfViewer" style="width: 100%; height: 800px;" hidden></iframe>
</div>


<script src="~/Content/vendor/jquery-3.2.1.min.js"></script>
<script>


    $(document).ready(function () {

        var resumen_tweet = "";

        $("#generar-sentencia").click(function (e) {
            e.preventDefault();

            var numExp = $("#num_exp").val();
            var fechaExp = $("#fecha_exp").val();
            var descExp = $("#desc_exp").val();

            var archivo = $("#archivo")[0].files[0];

            var formData = new FormData();
            formData.append("archivo", archivo);
            formData.append("num_expediente", numExp);
            formData.append("fecha_sentencia", fechaExp);
            formData.append("descripcion", descExp);
            $.ajax({
                type: "POST",
                url: "GenerarSentencia",
                data: formData,
                contentType: false,
                processData: false,
                success: function (response) {
                    if (response.success === true) {
                        var pdfUrl = "data:application/pdf;base64," + response.pdfBase64;
                        document.getElementById("pdfViewer").src = pdfUrl;
                        document.getElementById("pdfViewer").removeAttribute("hidden");
                        document.getElementById("generar-tweet").removeAttribute("hidden");

                        var downloadButton = document.createElement('a');
                        downloadButton.href = "data:application/octet-stream;base64," + response.fileBase64;
                        downloadButton.download = numExp+".docx"; 

                        downloadButton.innerHTML = `<button id="descargar-documento" type="button" class="btn btn-md btn-info btn-block">
                            <i class="fa fa-download fa-lg"></i>&nbsp;
                            <span id="payment-button-info">Descargar Documento</span>
                            <span id="payment-button-info2" style="display:none;">Descargando…</span>
                        </button>`;

                       
                        var botonContainer = document.getElementById("boton-container");
                        botonContainer.appendChild(downloadButton);
                        
                        downloadButton.addEventListener('click', function () {
                            window.open(downloadButton.href, '_blank');
                        });

                        resumen_tweet = response.resumen;

                    } else {
                        console.log("No se pudo generar el PDF.");
                    }
                },

                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });

        $("#generar-tweet").click(function () {
            var apiKey = "yourApiKey";

            var requestBody = {
                "model": "gpt-3.5-turbo",
                "messages": [
                    {
                        "role": "system",
                        "content": "Resume el contenido en 150 caracteres"
                    },
                    {
                        "role": "user",
                        "content": resumen_tweet
                    }
                ],
                "temperature": 0,
                "max_tokens": 1024
            };

            $.ajax({
                type: "POST",
                url: "https://api.openai.com/v1/chat/completions",
                headers: {
                    "Authorization": "Bearer " + apiKey,
                    "Content-Type": "application/json"
                },
                data: JSON.stringify(requestBody),
                dataType: "json",
                success: function (response) {
                    var summary = response.choices[0].message.content;
                    $("#contenido_tweet").text(summary);
                    document.getElementById("container-tweet").removeAttribute("hidden");

                },
                error: function () {
                    $("#summaryResult").text("Error al obtener el resumen.");
                }
            });
        });

    });
</script>

TCRD-GeneracionSentencia/TCRD-GeneracionSentencia/Views/Sentencias/Secuencia.cshtml

@using TCRD_GeneracionSentencia.Models

@{
    ViewBag.Title = "Index";
}

<style>

    .btn-info {
        color: #fff;
        background-color: rgb(122, 34, 46);
        border-color: rgb(122, 34, 46);
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">Secuencia</div>
                <div class="card-body">
                    @using (Html.BeginForm("Secuencia", "Sentencias", FormMethod.Post, new { @class = "au-form au-form--border" }))
                    {
                        @Html.AntiForgeryToken()
                        <form>
                            <div class="row">
                                <div class="col-9">
                                    <div class="form-group">
                                        <label for="secuencia" class="control-label mb-1">Nueva Secuencia</label>
                                        <input id="secuencia" name="secuencia" type="text" class="form-control secuencia" value="" data-val="true" data-val-required="Introduce la Secuencia"
                                               data-val-num_expp="Introduzca la nueva secuencia" placeholder="TC/XXXX/XX"
                                               autocomplete="num_exp">
                                        <span class="help-block" data-valmsg-for="secuencia" data-valmsg-replace="true"></span>
                                    </div>
                                </div>
                                <div class="col-3">
                                    <div class="form-group">
                                        <label for="cc-num_exp" class="control-label mb-1"></label>
                                        <button id="generar-sentencia" type="submit" class="btn btn-md btn-info btn-block">
                                            <i class="fa fa-save fa-lg"></i>&nbsp;
                                            <span id="payment-button-info">Establecer Secuencia</span>
                                            <span id="payment-button-info2" style="display:none;">Generando…</span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    }
                 </div>
            </div>
        </div>


    </div>

    <div class="row">
        <div class="col-lg-12">
            <!-- USER DATA-->
            <div class="user-data m-b-30">
                <h3 class="title-3 m-b-30">
                    <i class="zmdi zmdi-account-calendar"></i>Secuencias Generadas
                </h3>
                <div class="table-responsive table-data">
                    <table class="table">
                        <thead>
                            <tr>
                                <td>
                                </td>
                                <td>Num de la secuencia</td>
                                <td>Fecha</td>
                                <td>Usuario</td>
                            </tr>
                        </thead>
                        <tbody>

                            @{

                                foreach (var item in Model)
                                {
                                                        <tr>
                                                            <td>
                                                                <label class="au-checkbox">
                                                                    <input type="checkbox">
                                                                    <span class="au-checkmark"></span>
                                                                </label>
                                                            </td>
                                                            <td>
                                                                <div class="table-data__info">
                                                                    <h6>@item.secuencia</h6>

                                                                </div>
                                                            </td>
                                                            <td>
                                                                <span class="table-data__info">@item.fecha</span>
                                                            </td>
                                                            <td class="table-data__info">
                                                               @item.usuario
                                                            </td>
                                                            <td>
                                                                <span class="more">
                                                                    <i class="zmdi zmdi-more"></i>
                                                                </span>
                                                            </td>
                                                        </tr>
                                }
                            }


                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END USER DATA-->
        </div>
    </div>
</div>